import type { User, Course } from './types';

export const MOCK_USER: User = {
  id: 'u1',
  name: 'Demo User',
  email: 'demo@coursecompass.ai',
  interests: ['Machine Learning', 'Web Development', 'Data Science'],
};

export const COURSES: Course[] = [
  {
    id: 'c1',
    title: 'React - The Complete Guide (incl Hooks, React Router, Redux)',
    description: 'Dive in and learn React.js from scratch! Learn Reactjs, Hooks, Redux, React Routing, Animations, Next.js and way more!',
    longDescription: 'This course is your complete guide to React.js. You will learn all the core concepts of this popular JavaScript library, including components, props, state, hooks, context API, and Redux for state management. We will also cover React Router for navigation and Framer Motion for animations. By the end, you will build a complete, real-world application.',
    overview: 'A comprehensive course on React.js for beginners to advanced developers.',
    url: 'https://www.udemy.com/course/react-the-complete-guide-incl-hooks-react-router-redux/',
    imageUrl: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
    platform: 'Udemy',
    platformLogoUrl: 'https://i.imgur.com/2TEkd5E.png',
    instructor: 'Maximilian Schwarzmüller',
    subject: 'React',
    level: 'Intermediate',
    language: 'English',
    price: 6999,
    content: ['React Components & Props', 'State & Hooks (useState, useEffect)', 'React Router', 'Redux & Redux Toolkit', 'Next.js Basics', 'Building a Full-Stack App'],
    reviews: [
      { id: 'r1', userId: 'u2', username: 'Alice', createdAt: '2023-10-15', text: 'Amazing course! The instructor explains everything clearly. Highly recommended.', rating: { content: 5, instructor: 5, practicality: 5 }, upvotes: 120, downvotes: 2 },
      { id: 'r2', userId: 'u3', username: 'Bob', createdAt: '2023-10-20', text: 'Very comprehensive, but sometimes a bit too fast for a complete beginner.', rating: { content: 5, instructor: 4, practicality: 4 }, upvotes: 45, downvotes: 5 },
    ],
  },
  {
    id: 'c2',
    title: 'The Complete 2023 Web Development Bootcamp',
    description: 'Become a Full-Stack Web Developer with just one course. HTML, CSS, Javascript, Node, React, MongoDB, Web3 and DApps.',
    longDescription: 'Covering all the latest technologies, this course will take you from zero to full-stack developer. You will learn the entire technology stack, from frontend technologies like HTML, CSS, and JavaScript, to backend technologies like Node.js and MongoDB. We also dive into modern libraries like React and even explore the exciting world of Web3.',
    overview: 'The only course you need to learn web development.',
    url: 'https://www.udemy.com/course/the-complete-web-development-bootcamp/',
    imageUrl: 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
    platform: 'Udemy',
    platformLogoUrl: 'https://i.imgur.com/2TEkd5E.png',
    instructor: 'Dr. Angela Yu',
    subject: 'JavaScript',
    level: 'Beginner',
    language: 'English',
    price: 7499,
    content: ['HTML5 & CSS3', 'Modern JavaScript (ES6+)', 'Node.js & Express', 'MongoDB', 'React.js', 'Web3 & DApps'],
    reviews: [
      { id: 'r3', userId: 'u4', username: 'Charlie', createdAt: '2023-09-01', text: 'Angela is the best teacher on Udemy. The content is engaging and easy to follow.', rating: { content: 5, instructor: 5, practicality: 5 }, upvotes: 250, downvotes: 3 },
    ],
  },
  {
    id: 'c3',
    title: 'Machine Learning A-Z™: AI, Python & R',
    description: 'Learn to create Machine Learning Algorithms in Python and R from two Data Science experts. Code templates included.',
    longDescription: 'This course provides a thorough introduction to Machine Learning and Data Science. You will learn about various ML models like regression, classification, clustering, and deep learning. The course is very hands-on, with practical examples in both Python and R. You get all the code templates to use in your own projects.',
    overview: 'Master Machine Learning with Python & R.',
    url: 'https://www.udemy.com/course/machinelearning/',
    imageUrl: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
    platform: 'Udemy',
    platformLogoUrl: 'https://i.imgur.com/2TEkd5E.png',
    instructor: 'Kirill Eremenko, Hadelin de Ponteves',
    subject: 'Machine Learning',
    level: 'Beginner',
    language: 'English',
    price: 6999,
    content: ['Data Preprocessing', 'Regression Models', 'Classification Models', 'Clustering', 'Deep Learning Basics', 'Natural Language Processing'],
    reviews: [
        { id: 'r4', userId: 'u5', username: 'David', createdAt: '2023-11-05', text: 'Great content, but the R sections feel a bit outdated. The Python part is fantastic though.', rating: { content: 4, instructor: 4, practicality: 5 }, upvotes: 78, downvotes: 10 },
    ],
  },
  {
    id: 'c4',
    title: 'Python for Data Science and Machine Learning Bootcamp',
    description: 'Learn how to use NumPy, Pandas, Seaborn, Matplotlib, Plotly, Scikit-Learn, Machine Learning, Tensorflow, and more!',
    longDescription: 'This is a comprehensive course for learning Python for Data Science and Machine Learning. It covers everything from basic Python to advanced data analysis and machine learning libraries. You will work on several projects to apply what you have learned.',
    overview: 'A complete bootcamp on Python for data science and ML.',
    url: 'https://www.udemy.com/course/python-for-data-science-and-machine-learning-bootcamp/',
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
    platform: 'Udemy',
    platformLogoUrl: 'https://i.imgur.com/2TEkd5E.png',
    instructor: 'Jose Portilla',
    subject: 'Data Science',
    level: 'Intermediate',
    language: 'English',
    price: 7999,
    content: ['Python Crash Course', 'NumPy Arrays', 'Pandas DataFrames', 'Matplotlib & Seaborn', 'Scikit-Learn', 'TensorFlow'],
    reviews: [
        { id: 'r5', userId: 'u6', username: 'Eve', createdAt: '2023-08-12', text: 'Jose is a great instructor. The course is packed with information and the projects are very useful.', rating: { content: 5, instructor: 5, practicality: 5 }, upvotes: 150, downvotes: 1 },
    ],
  },
   {
    id: 'c5',
    title: 'SQL - MySQL for Data Analytics and Business Intelligence',
    description: 'SQL that will get you hired – A complete SQL bootcamp with MySQL, Data Analysis, and Data Visualization.',
    longDescription: 'This course will teach you everything you need to know about SQL for data analysis and business intelligence. You will start with the basics of SQL and MySQL and move on to advanced topics like joins, subqueries, and window functions. The course also covers data visualization with Tableau.',
    overview: 'Become an expert in SQL and MySQL.',
    url: 'https://www.udemy.com/course/sql-mysql-for-data-analytics-and-business-intelligence/',
    imageUrl: 'https://images.unsplash.com/photo-1529400971008-f566de0e6dfc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80',
    platform: 'Udemy',
    platformLogoUrl: 'https://i.imgur.com/2TEkd5E.png',
    instructor: 'Abhishek and Pukhraj',
    subject: 'SQL',
    level: 'Beginner',
    language: 'English',
    price: 0,
    content: ['SQL Basics', 'MySQL Workbench', 'Database Joins', 'Advanced SQL', 'Data Analysis Tasks', 'Tableau Integration'],
    reviews: [
        { id: 'r6', userId: 'u7', username: 'Frank', createdAt: '2023-10-01', text: 'Excellent free course! Covers a lot of ground and the exercises are very helpful.', rating: { content: 5, instructor: 5, practicality: 5 }, upvotes: 300, downvotes: 0 },
    ],
  },
  {
    id: 'c6',
    title: 'Advanced CSS and Sass: Flexbox, Grid, Animations and More!',
    description: 'The most advanced and modern CSS course on the internet: master flexbox, CSS Grid, responsive design, and so much more.',
    longDescription: 'This course is for developers who want to take their CSS skills to the next level. You will master modern CSS features like Flexbox and CSS Grid, and learn advanced concepts like Sass, responsive design, and animations. The course includes a huge project where you build a beautiful, responsive website from scratch.',
    overview: 'Go from a CSS beginner to an advanced, confident, and independent front-end developer.',
    url: 'https://www.udemy.com/course/advanced-css-and-sass/',
    imageUrl: 'https://images.unsplash.com/photo-1507721999472-8ed4421b432b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80',
    platform: 'Udemy',
    platformLogoUrl: 'https://i.imgur.com/2TEkd5E.png',
    instructor: 'Jonas Schmedtmann',
    subject: 'JavaScript',
    level: 'Advanced',
    language: 'English',
    price: 6999,
    content: ['Advanced CSS Selectors', 'Flexbox', 'CSS Grid', 'Sass & NPM', 'Responsive Design', 'CSS Animations'],
    reviews: [
        { id: 'r7', userId: 'u8', username: 'Grace', createdAt: '2023-09-20', text: 'Jonas is a fantastic teacher. His courses are always top-notch, and this one is no exception. My CSS skills have improved dramatically.', rating: { content: 5, instructor: 5, practicality: 5 }, upvotes: 180, downvotes: 2 },
    ],
  },
  {
    id: 'c7',
    title: 'Google UX Design Professional Certificate',
    description: 'This is your path to a career in UX design. In this program, you’ll learn in-demand skills that will have you job-ready in less than 6 months.',
    longDescription: 'Prepare for a new career in the high-growth field of UX design, no experience or degree required. Get professional training designed by Google and get on the fast-track to a competitively paid job. There are currently 138,000 U.S. job openings in UX design with a median entry-level salary of $112,000.',
    overview: 'Follow the design process: empathize with users, define pain points, ideate solutions, create wireframes and prototypes, test and iterate on designs.',
    url: 'https://www.coursera.org/professional-certificates/google-ux-design',
    imageUrl: 'https://images.unsplash.com/photo-1581291518857-4e261b9ff24e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
    platform: 'Coursera',
    platformLogoUrl: 'https://i.imgur.com/gzGfOai.png',
    instructor: 'Google Career Certificates',
    subject: 'UI/UX Design',
    level: 'Beginner',
    language: 'English',
    price: 3999,
    content: ['Foundations of UX Design', 'Start the UX Design Process', 'Build Wireframes & Low-Fidelity Prototypes', 'Conduct UX Research', 'Create High-Fidelity Designs', 'Design a User Experience for Social Good'],
    reviews: [
        { id: 'r8', userId: 'u9', username: 'Heidi', createdAt: '2023-11-01', text: 'An incredible amount of information and a great way to start a portfolio. A must for aspiring UX designers.', rating: { content: 5, instructor: 5, practicality: 5 }, upvotes: 210, downvotes: 4 },
    ],
  },
  {
    id: 'c8',
    title: 'AWS Certified Solutions Architect - Associate SAA-C03',
    description: 'Pass the AWS Certified Solutions Architect - Associate exam! 25 hours of content and 6 practice exams.',
    longDescription: 'Want to pass the AWS Certified Solutions Architect - Associate exam? Want to become Amazon Web Services Certified? Do this course! This is the most comprehensive and hands-on course for the SAA-C03 exam. It is a cloud certification that is in high demand in the IT industry.',
    overview: 'This is the #1 course to pass your AWS Certified Solutions Architect Associate exam.',
    url: 'https://www.udemy.com/course/aws-certified-solutions-architect-associate-saa-c03/',
    imageUrl: 'https://images.unsplash.com/photo-1587293852726-70cdb122c29a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80',
    platform: 'Udemy',
    platformLogoUrl: 'https://i.imgur.com/2TEkd5E.png',
    instructor: 'Stephane Maarek',
    subject: 'Cloud Computing',
    level: 'Intermediate',
    language: 'English',
    price: 6499,
    content: ['Identity and Access Management (IAM)', 'EC2 Fundamentals', 'S3, Glacier & Snowball', 'Databases on AWS', 'Virtual Private Cloud (VPC)', 'Serverless & Docker on AWS'],
    reviews: [
        { id: 'r9', userId: 'u10', username: 'Ivan', createdAt: '2023-10-28', text: 'Stephane is the best when it comes to AWS. This course is all you need to pass the exam. Clear, concise, and to the point.', rating: { content: 5, instructor: 5, practicality: 5 }, upvotes: 195, downvotes: 1 },
    ],
  },
  {
    id: 'c9',
    title: 'Go: The Complete Developer\'s Guide (Golang)',
    description: 'Master the fundamentals and advanced features of the Go Programming Language (Golang)',
    longDescription: 'This course is the most comprehensive resource for learning the Go programming language. It includes hours of video content, along with hundreds of exercises and projects. You will go from a complete beginner to a confident Go developer.',
    overview: 'The most comprehensive Go course available online.',
    url: 'https://www.udemy.com/course/go-the-complete-developers-guide/',
    imageUrl: 'https://images.unsplash.com/photo-1618477388954-7852f32655ec?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
    platform: 'Udemy',
    platformLogoUrl: 'https://i.imgur.com/2TEkd5E.png',
    instructor: 'Stephen Grider',
    subject: 'Go',
    level: 'Beginner',
    language: 'English',
    price: 5999,
    content: ['Go Basics', 'Structs and Interfaces', 'Concurrency & Goroutines', 'Channels', 'Testing', 'Building Real-world Projects'],
    reviews: [
        { id: 'r10', userId: 'u11', username: 'Judy', createdAt: '2023-08-15', text: 'Stephen explains complex topics in a very simple way. His diagrams are legendary. Best Go course out there.', rating: { content: 5, instructor: 5, practicality: 5 }, upvotes: 130, downvotes: 0 },
    ],
  },
  {
    id: 'c10',
    title: 'The Complete Digital Marketing Course - 12 Courses in 1',
    description: 'Master Digital Marketing: SEO, Social Media, Facebook, YouTube, Email Marketing, Google Analytics & AdWords.',
    longDescription: 'With 12 major online marketing topics covered, this bestselling course is the most comprehensive digital marketing course available. We cover everything from SEO to Facebook Ads to Google Analytics. You\'ll learn the proper techniques and strategies for each section, and then see how these strategies are implemented in real-world projects.',
    overview: 'Learn Digital Marketing from A-Z. Grow your business or land your dream marketing job.',
    url: 'https://www.udemy.com/course/learn-digital-marketing-course/',
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1115&q=80',
    platform: 'Udemy',
    platformLogoUrl: 'https://i.imgur.com/2TEkd5E.png',
    instructor: 'Rob Percival, Daragh Walsh',
    subject: 'Digital Marketing',
    level: 'Beginner',
    language: 'English',
    price: 8499,
    content: ['Market Research', 'WordPress Setup', 'Email Marketing', 'Search Engine Optimization (SEO)', 'YouTube Marketing', 'Facebook & Instagram Ads'],
    reviews: [
        { id: 'r11', userId: 'u12', username: 'Kevin', createdAt: '2023-11-02', text: 'So much value in one course! It\'s like a marketing degree. Highly practical.', rating: { content: 5, instructor: 4, practicality: 5 }, upvotes: 95, downvotes: 3 },
    ],
  },
  {
    id: 'c11',
    title: 'The Complete Cyber Security Course : Hackers Exposed!',
    description: 'Volume 1 : Become a Cyber Security Specialist, Learn How to Stop Hackers, Prevent Hacking, Learn IT Security & INFOSEC.',
    longDescription: 'This course is for anyone who wants to become a cyber security specialist. It covers the fundamental security concepts, shows you the tools and techniques used by hackers, and teaches you how to defend against them. You will learn about threat modeling, encryption, firewalls, and much more.',
    overview: 'Learn a practical skill-set in defeating all online threats, including - advanced hackers, trackers, malware and all Internet nastiness.',
    url: 'https://www.udemy.com/course/the-complete-internet-security-privacy-course-volume-1/',
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-5f61d25c0940?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
    platform: 'Udemy',
    platformLogoUrl: 'https://i.imgur.com/2TEkd5E.png',
    instructor: 'Nathan House',
    subject: 'Cybersecurity',
    level: 'Beginner',
    language: 'English',
    price: 7999,
    content: ['Threat Landscape', 'Encryption', 'Darknet & Malware', 'Operating System Security', 'Firewalls & Network Security', 'Bug Bounties'],
    reviews: [
        { id: 'r12', userId: 'u13', username: 'Laura', createdAt: '2023-09-30', text: 'A real eye-opener. Nathan is incredibly knowledgeable and makes security accessible. A must-watch for anyone who uses the internet.', rating: { content: 5, instructor: 5, practicality: 5 }, upvotes: 115, downvotes: 1 },
    ],
  }
];